sudo: false
language: scala

scala:
  - 2.11.11
  - 2.12.2

jdk:
  - oraclejdk8

install:
  - pip install --user codecov

script:
  sbt ++$TRAVIS_SCALA_VERSION clean coverage test scalastyle unidoc coverageReport && codecov;
