language: scala

scala:
  - 2.11.12
  - 2.12.10

jdk:
  - openjdk8

sbt_args: -J-Xmx8192M

script:
  sbt ++$TRAVIS_SCALA_VERSION clean test;

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
